### ISSUE TITLE
More descriptions in README

### ISSUE THREAD

**Issue by gaheens** [cpreid2/gdc-rnaseq-tool#1]
The tool works good! Just recommend more descriptions in the README. For example:

1) The README has the bulleted list of RNA-Seq and miRNA Expression Quantification. Recommend creating a section on Inputs and a section on Outputs and merging the bulleted list into the Inputs section with more descriptions. The Outputs section could have a description of Merged_Counts, Merged_FPKM, Merged_FPKM-UQ, Merged_miRNA_Counts, Merged_miRNA_rpmm
2) In the quick start, add a step to download the gdc-rnaseq-tool. I understand this should be intuitive but it is a step.
3) I am running the tool using Python 3.6 on Windows but do not specify "python3" as the executable is just "python".

**Comment by hsahni** [comment]
Hi Colins,

1. I think we need to describe the problem domain as in what problem this tool is helping solve and how is it doing it (uses manifest to download the files, extracts _xyz_ from  downloaded files and generates a tabular result of _adc_ etc.

2. Further describe the input _RNA/MiRNA expression data_
- _Does the input need to be only Transcriptome Profiling,isoform Expression Quantification miRNA-Seq TSV files ?_
- _Does it work for all projects or just TCGA ?_
- _Do the files need to be open access only?_
- _Works on GDC harmonized Portal files & legacy files? or just harmonized portal files._
- _Perhaps add a link to an example gdc query_

3. Description of what the values represent within each of the output files would be very helpful
```
--------------
Creating merged HTSeq - Counts File... ( Merged_Counts.tsv )
--------------
Creating merged HTSeq - FPKM-UQ File... ( Merged_FPKM-UQ.tsv )
--------------
Creating merged HTSeq - FPKM File... ( Merged_FPKM.tsv )
--------------
Creating merged miRNASeq Counts File... ( Merged_miRNA_Counts.tsv )
Creating merged miRNASeq rpmm File... ( Merged_miRNA_rpmm.tsv )
```
4. I have been using python 2.7 so had to install python 3 from scratch (Installed python36.32)
so I also had to also install requests package
```
C:\Python36-32>py gdc-rnaseq-tool.py -h
Traceback (most recent call last):
  File "gdc-rnaseq-tool.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests
```
5. BTW (_on windows_) I generally use the following to install packages
`py -m pip install <<package>>`

**Comment by cpreid2** [comment]
@gaheens Thanks for the great feedback!  I've updated the readme with your suggestions.
